### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by Ketherz** [offsecginger/CTFd-Docker-Challenges#1]
Hello! So, i'm trying to use your pluggin to host a ctf powered by docker. The only problem is that when i go to docker_config there the following error : 

```python
Traceback (most recent call last):
  File "/home/ketherz/.local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ketherz/.local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/ketherz/.local/lib/python3.8/site-packages/flask_restx/api.py", line 639, in error_router
    return original_handler(e)
  File "/home/ketherz/.local/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ketherz/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ketherz/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ketherz/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ketherz/.local/lib/python3.8/site-packages/flask_restx/api.py", line 639, in error_router
    return original_handler(e)
  File "/home/ketherz/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ketherz/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ketherz/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ketherz/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ketherz/logiciel/CTFd/CTFd/utils/decorators/__init__.py", line 133, in admins_only_wrapper
    return f(*args, **kwargs)
  File "/home/ketherz/logiciel/CTFd/CTFd/plugins/docker_challenges/__init__.py", line 137, in docker_config
    return render_template("docker_config.html", config=dconfig, form=form, repos=selected_repos)
  File "/home/ketherz/.local/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/ketherz/.local/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/ketherz/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/ketherz/.local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/ketherz/.local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/ketherz/logiciel/CTFd/CTFd/plugins/docker_challenges/templates/docker_config.html", line 1, in top-level template code
    {% extends 'admin/base.html' %}
  File "/home/ketherz/logiciel/CTFd/CTFd/themes/admin/templates/base.html", line 124, in top-level template code
    {% block content %}
  File "/home/ketherz/logiciel/CTFd/CTFd/plugins/docker_challenges/templates/docker_config.html", line 63, in block "content"
    {% if key in repos %}
TypeError: argument of type 'NoneType' is not iterable

```

I think it's because of a problem in the database resulting in the variable selected_repos getting equal to none. I can get it to work by bypassing the repos = selected_repos variable but it lead to 2  other error.
 
1 - When i start a docker challenge,  the container is not created .
2 - When i try to erase the challenge the database is locked. 

It make me think that the database is the problem here so i would like to know if there is extra step to do with the database to set-up the plugin ? Or if i do something wrong ? The problem does not appear if there is 0 images in the docker naturally and images are detected in the docker challenge creator even with the error above. But starting a challenge with the website will lead to that kind of error.

```python
Traceback (most recent call last):
  File "/home/ketherz/.local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ketherz/.local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/ketherz/.local/lib/python3.8/site-packages/flask_restx/api.py", line 638, in error_router
    return original_handler(f)
  File "/home/ketherz/.local/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ketherz/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ketherz/.local/lib/python3.8/site-packages/flask_restx/api.py", line 636, in error_router
    return self.handle_error(e)
  File "/home/ketherz/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ketherz/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ketherz/.local/lib/python3.8/site-packages/flask_restx/api.py", line 638, in error_router
    return original_handler(f)
  File "/home/ketherz/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ketherz/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ketherz/.local/lib/python3.8/site-packages/flask_restx/api.py", line 636, in error_router
    return self.handle_error(e)
  File "/home/ketherz/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ketherz/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ketherz/.local/lib/python3.8/site-packages/flask_restx/api.py", line 375, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/ketherz/.local/lib/python3.8/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/ketherz/.local/lib/python3.8/site-packages/flask_restx/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/ketherz/logiciel/CTFd/CTFd/utils/decorators/__init__.py", line 87, in authed_only_wrapper
    return f(*args, **kwargs)
  File "/home/ketherz/logiciel/CTFd/CTFd/plugins/docker_challenges/__init__.py", line 589, in get
    portsbl = get_unavailable_ports(docker)
  File "/home/ketherz/logiciel/CTFd/CTFd/plugins/docker_challenges/__init__.py", line 255, in get_unavailable_ports
    r = requests.get(url="%s/containers/json?all=1" % URL_TEMPLATE, cert=CERT, verify=ca_file.name)
UnboundLocalError: local variable 'CERT' referenced before assignment
```
I will continue to search a solution for those errors and will mark the solution if i find one. If anyone has an idea let me know too! Same if you need precision. Thanks ! (I use the python debug version of ctfd)

**Comment by Ketherz** [comment]
Hey thanks for the fast reply :) ! I just saw that in the code, i'm going to use TLS to see if the plugin work with it, and I will write over there if solve my error.

**Comment by Ketherz** [comment]
Yup allowing TLS on docker was the answer! Thanks for the help, the nonetype error is still here but it's not a big deal since i can override it :) 
The error about the database being locked by challenge removal is still up too, i will try to investigate and post an answer if you want me too, (and if it's not due to a bad setup that i would have done)

**Comment by minhnq1618** [comment]
Hi @Ketherz , i am also running into some trouble using the plugin, i am a noob so could you help me out please ? XD

**Comment by offsecginger** [comment]
Please provide your CTFd version and what you're attempting to do with the
error you're receiving.

**Comment by offsecginger** [comment]
Figured out the issue. I wrote this in python2.7 and python3 requires certain types to be defined. The issue we ran into is that `None` is declared in line 133, throwing an error. This has only been tested with TLS. I'm making a few more changes, but this should be good to go for 3.3.0. @Ketherz

**Comment by offsecginger** [comment]
This issue is now resolved.
