### ISSUE TITLE
Cannot delete Docker Challenges

### ISSUE THREAD

**Issue by vnthn** [offsecginger/CTFd-Docker-Challenges#6]
If you try to reset the CTFd it will crash and report "500 Internal Server Error".
If you try to  delete a docker challenge it won't delete the challenge but silenty report the following error to the logs.
I think if you try to reset CTFd it will also try to delete the remaining challenges and call the same function.
CTFd throws the following error in both cases:
```
172.23.0.1 - - [24/Jun/2021:10:55:31 +0000] "DELETE /api/v1/challenges/3 HTTP/1.0" 500 37 "http://127.0.0.1/admin/challenges" "Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"
ERROR [CTFd] Exception on /api/v1/challenges/5 [DELETE]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1284, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`ctfd`.`docker_challenge`, CONSTRAINT `docker_challenge_ibfk_1` FOREIGN KEY (`id`) REFERENCES `challenges` (`id`))')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_restx/api.py", line 375, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_restx/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/CTFd/CTFd/utils/decorators/__init__.py", line 133, in admins_only_wrapper
    return f(*args, **kwargs)
  File "/opt/CTFd/CTFd/api/v1/challenges.py", line 541, in delete
    chal_class.delete(challenge)
  File "/opt/CTFd/CTFd/plugins/docker_challenges/__init__.py", line 489, in delete
    Challenges.query.filter_by(id=challenge.id).delete()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3872, in delete
    delete_op.exec_()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1697, in exec_
    self._do_exec()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1928, in _do_exec
    self._execute_stmt(delete_stmt)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1702, in _execute_stmt
    self.result = self.query._execute_crud(stmt, self.mapper)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3514, in _execute_crud
    return conn.execute(stmt, self._params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1020, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1324, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1518, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1284, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.IntegrityError: (pymysql.err.IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`ctfd`.`docker_challenge`, CONSTRAINT `docker_challenge_ibfk_1` FOREIGN KEY (`id`) REFERENCES `challenges` (`id`))')
[SQL: DELETE FROM challenges WHERE challenges.id = %(id_1)s]
[parameters: {'id_1': 5}]
(Background on this error at: http://sqlalche.me/e/gkpj)
```

So it seems like there is something referenced which shouldn't be referenced or something is not properly deleted in the function `delete(challenge)` inside the ChallengeType definition in the class `DockerChallengeType(BaseChallenge)`.

**Comment by dustinwloring1988** [comment]
Could you please make a public repo with your CTFd and CTFd docker plugin together. I will then download it and try to trouble shoot it when I get home.

**Comment by vnthn** [comment]
I made a public repo [CTFd-Docker-Challenges](https://github.com/vnthn/CTFd-Docker-Challenges) where I changed a few things in the plugin, refactoring and bug fixing. I also use a fork of [CTFd](https://github.com/vnthn/CTFd.git) where the Docker socket is mounted inside the container to avoid the insecure http communication and the non working https communication. But this should not affect this issue.

You can use the Makefile in this [gist](https://gist.github.com/vnthn/3b17d2fa4c93c685a8544da4c85d5843) to deploy my version of CTFd and the plugin.

**Comment by offsecginger** [comment]
Looks like the latest Merge fixes this issue. #7

**Comment by offsecginger** [comment]
J/K It's not fixed.

**Comment by Kuchenpirat** [comment]
#13 should fix the issue
